import React from 'react';
import { 
  X, 
  Sparkles, 
  FileText, 
  ShieldAlert, 
  CheckCircle2, 
  TrendingUp, 
  AlertTriangle,
  Printer
} from 'lucide-react';

export default function CfoBriefModal({
  brief,
  isLoading,
  onClose
}) {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="modal-backdrop">
      <div className="modal-container glass-panel modal-lg animate-fade-in printable-container">
        {/* Header */}
        <div className="modal-header">
          <div className="modal-title-group">
            <div className="modal-badge-row">
              <span className="badge badge-amber flex-center-gap">
                <FileText size={13} />
                <span>EXECUTIVE INTELLIGENCE</span>
              </span>
              <span className="badge badge-indigo">BOARD & CFO LEVEL</span>
            </div>
            <h2 className="modal-title">CFO Risk & Strategic Action Brief</h2>
            <p className="modal-subtitle">
              Generated by Autonomous Finance Controller • {brief?.generated_at || new Date().toLocaleString()}
            </p>
          </div>

          <div className="modal-header-actions">
            <button className="btn btn-secondary no-print" onClick={handlePrint} title="Print report">
              <Printer size={16} />
              <span>Print</span>
            </button>
            <button className="modal-close-btn no-print" onClick={onClose}>
              <X size={20} />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="modal-body-scroll">
          {isLoading ? (
            <div className="ai-loading-box">
              <Sparkles className="animate-spin text-amber" size={32} />
              <p className="font-medium mt-3">Synthesizing Executive CFO Briefing...</p>
              <span className="text-xs text-muted">Calculating financial health scores and strategic risk vectors</span>
            </div>
          ) : brief ? (
            <div className="cfo-brief-content">
              {/* Financial Health Score Banner */}
              <div className="health-score-banner">
                <div className="health-score-value-box">
                  <span className="health-score-number mono">{brief.financial_health_score}</span>
                  <span className="health-score-label">FINANCIAL HEALTH</span>
                </div>
                <div className="health-score-narrative">
                  <h4 className="font-semibold text-lg">Executive Summary</h4>
                  <p className="ai-narrative-text mt-1">{brief.executive_summary}</p>
                </div>
              </div>

              {/* Match Rate & Leakage Analysis */}
              <div className="two-col-grid mt-4">
                <div className="ai-card">
                  <div className="ai-card-header">
                    <TrendingUp size={18} className="text-emerald" />
                    <h4>Match Rate Analysis</h4>
                  </div>
                  <p className="ai-narrative-text mt-2">{brief.match_rate_analysis}</p>
                </div>

                <div className="ai-card">
                  <div className="ai-card-header">
                    <AlertTriangle size={18} className="text-rose" />
                    <h4>Revenue Leakage Breakdown</h4>
                  </div>
                  <p className="ai-narrative-text mt-2">{brief.unresolved_leakage_breakdown}</p>
                </div>
              </div>

              {/* Top Vulnerabilities */}
              <div className="ai-card mt-4">
                <div className="ai-card-header">
                  <ShieldAlert size={18} className="text-amber" />
                  <h4>Systemic Risk Vectors & Vulnerabilities</h4>
                </div>
                <ul className="vulnerability-list mt-2">
                  {brief.top_vulnerabilities?.map((vuln, i) => (
                    <li key={i} className="vulnerability-item">
                      <span className="vuln-bullet">•</span>
                      <span>{vuln}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Strategic Action Items */}
              <div className="ai-card mt-4">
                <div className="ai-card-header">
                  <CheckCircle2 size={18} className="text-cyan" />
                  <h4>Prioritized CFO Action Items</h4>
                </div>
                <div className="action-items-grid mt-3">
                  {brief.strategic_action_items?.map((item, i) => (
                    <div key={i} className="action-item-card">
                      <div className="action-item-header">
                        <span className={`priority-badge priority-${(item.priority || 'MEDIUM').toLowerCase()}`}>
                          {item.priority || 'MEDIUM'}
                        </span>
                        <span className="owner-tag mono">{item.owner || 'FINANCE TEAM'}</span>
                      </div>
                      <h5 className="action-item-title">{item.title || item.action}</h5>
                      <p className="action-item-desc text-muted text-sm mt-1">{item.description}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          ) : null}
        </div>
      </div>
    </div>
  );
}
